services:
  mongo:
    build:
      context: ./mongodb_replica
      args:
        MONGO_VERSION: 4
    environment:
      MONGO_REPLICA_HOST: 127.0.0.1
      MONGO_REPLICA_PORT: 27017
      MONGO_INITDB_DATABASE: "codepair"
      MONGO_COMMAND: "mongo"
    ports:
      - "27017:27017"
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "mongo",
          "admin",
          "--port",
          "27017",
          "--eval",
          "db.adminCommand('ping').ok",
        ]
      interval: 5s
      timeout: 2s
      retries: 20
  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
