# In this minmal YAML below, only the required fields that do not have defaults
# are provided. For fields with URL validation and defaults, we supply valid values when needed.

OAuth:
  Github:
    ClientID: "config-minimal-yaml"
    ClientSecret: "config-minimal-yaml"
    CallbackURL: "http://config-minimal-yaml/auth/login/github"
    TokenURL: "http://config-minimal-yaml/token"  # provided but not default; note valid URL format
  FrontendBaseURL: "http://config-minimal-yaml"


JWT:
  AccessTokenSecret: "config-minimal-yaml"
  RefreshTokenSecret: "config-minimal-yaml"


Mongo:
  ConnectionURI: "mongodb://config-minimal-yaml-mongo:27017/codepair"
  DatabaseName: "config-minimal-yaml-codepair"

Storage:
  Provider: "minio"
  Minio:
    Bucket: "config-minimal-yaml"
    Endpoint: "http://config-minimal-yaml:9000"
    AccessKey: "config-minimal-yaml"
    SecretKey: "config-minimal-yaml"
