# This is a configuration file for test.
# In this file, only the required fields that do not have defaults are provided.
# For fields with URL validation and defaults, we should supply valid values when needed.

Server:
  Port: 3003

OAuth:
  Github:
    ClientID: "config_client_id"
    ClientSecret: "config_client_secret"
    CallbackURL: "https://config.example.com/auth/login/github"
    AuthorizationURL: "https://config.example.com/login/oauth/authorize"
    TokenURL: "https://config.example.com/login/oauth/access_token"
    UserProfileURL: "https://config.example.com/api/user"
  FrontendBaseURL: "http://config-frontend:5173"

JWT:
  AccessTokenSecret: "config_access_token_secret"
  AccessTokenExpirationTime: "24h"
  RefreshTokenSecret: "config_refresh_token_secret"
  RefreshTokenExpirationTime: "168h"

Yorkie:
  APIAddr: "https://config-yorkie:8080"
  ProjectName: "config_project"
  ProjectSecretKey: "config_project_secret"
  Intelligence: ""

Mongo:
  ConnectionTimeout: "10s"
  ConnectionURI: "mongodb://config-mongo:27017/codepair"
  PingTimeout: "5s"
  DatabaseName: "config_codepair"

Storage:
  Provider: "s3"

  Minio:
    Bucket: "config-storage"
    Endpoint: "https://config-minio:9000"
    AccessKey: "config_minioadmin"
    SecretKey: "config_minioadmin"

  S3:
    Bucket: "default-storage"
    Region: "us-east-1"
    AccessKey: "aws_access_key"
    SecretKey: "aws_secret_key"
