Server:
  Port: 3001

Auth:
  Github:
    # WARNING: Replace these values with your GitHub OAuth credentials
    ClientID: ""
    ClientSecret: ""
    CallbackURL: "http://localhost:3000/auth/login/github"
    AuthorizationURL: "https://github.com/login/oauth/authorize"
    TokenURL: "https://github.com/login/oauth/access_token"
    UserProfileURL: "https://api.github.com/user"
  FrontendBaseURL: "http://localhost:5173"

JWT:
  # WARNING: Use strong, unique secrets in production
  AccessTokenSecret: "<STRONG_RANDOM_SECRET>"
  AccessTokenExpirationTime: "24h"
  RefreshTokenSecret: "<STRONG_RANDOM_SECRET>"
  RefreshTokenExpirationTime: "168h"

Yorkie:
  APIAddr: "http://localhost:8080"
  ProjectName: "default"
  ProjectSecretKey: ""

Mongo:
  ConnectionTimeout: "10s"
  ConnectionURI: "mongodb://localhost:27017/codepair"
  PingTimeout: "5s"
  DatabaseName: "codepair"

Storage:
  Provider: "minio"       # or "s3"

  Minio:
    Bucket: "default-storage"
    Endpoint: "http://localhost:9000"
    AccessKey: "minioadmin"
    SecretKey: "minioadmin"

  S3:
    Bucket: "default-storage"
    Region: "us-east-1"
    AccessKey: "aws_access_key"
    SecretKey: "aws_secret_key"
