// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: codepair/v1/check.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CheckService_CheckNameConflict_FullMethodName = "/codepair.v1.CheckService/CheckNameConflict"
	CheckService_CheckYorkie_FullMethodName       = "/codepair.v1.CheckService/CheckYorkie"
)

// CheckServiceClient is the client API for CheckService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CheckServiceClient interface {
	// POST /check/name-conflict
	CheckNameConflict(ctx context.Context, in *CheckNameConflictRequest, opts ...grpc.CallOption) (*CheckNameConflictResponse, error)
	// POST /check/yorkie
	CheckYorkie(ctx context.Context, in *CheckYorkieRequest, opts ...grpc.CallOption) (*CheckYorkieResponse, error)
}

type checkServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCheckServiceClient(cc grpc.ClientConnInterface) CheckServiceClient {
	return &checkServiceClient{cc}
}

func (c *checkServiceClient) CheckNameConflict(ctx context.Context, in *CheckNameConflictRequest, opts ...grpc.CallOption) (*CheckNameConflictResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckNameConflictResponse)
	err := c.cc.Invoke(ctx, CheckService_CheckNameConflict_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *checkServiceClient) CheckYorkie(ctx context.Context, in *CheckYorkieRequest, opts ...grpc.CallOption) (*CheckYorkieResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckYorkieResponse)
	err := c.cc.Invoke(ctx, CheckService_CheckYorkie_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CheckServiceServer is the server API for CheckService service.
// All implementations must embed UnimplementedCheckServiceServer
// for forward compatibility.
type CheckServiceServer interface {
	// POST /check/name-conflict
	CheckNameConflict(context.Context, *CheckNameConflictRequest) (*CheckNameConflictResponse, error)
	// POST /check/yorkie
	CheckYorkie(context.Context, *CheckYorkieRequest) (*CheckYorkieResponse, error)
	mustEmbedUnimplementedCheckServiceServer()
}

// UnimplementedCheckServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCheckServiceServer struct{}

func (UnimplementedCheckServiceServer) CheckNameConflict(context.Context, *CheckNameConflictRequest) (*CheckNameConflictResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckNameConflict not implemented")
}
func (UnimplementedCheckServiceServer) CheckYorkie(context.Context, *CheckYorkieRequest) (*CheckYorkieResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckYorkie not implemented")
}
func (UnimplementedCheckServiceServer) mustEmbedUnimplementedCheckServiceServer() {}
func (UnimplementedCheckServiceServer) testEmbeddedByValue()                      {}

// UnsafeCheckServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CheckServiceServer will
// result in compilation errors.
type UnsafeCheckServiceServer interface {
	mustEmbedUnimplementedCheckServiceServer()
}

func RegisterCheckServiceServer(s grpc.ServiceRegistrar, srv CheckServiceServer) {
	// If the following call pancis, it indicates UnimplementedCheckServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CheckService_ServiceDesc, srv)
}

func _CheckService_CheckNameConflict_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckNameConflictRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CheckServiceServer).CheckNameConflict(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CheckService_CheckNameConflict_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CheckServiceServer).CheckNameConflict(ctx, req.(*CheckNameConflictRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CheckService_CheckYorkie_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckYorkieRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CheckServiceServer).CheckYorkie(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CheckService_CheckYorkie_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CheckServiceServer).CheckYorkie(ctx, req.(*CheckYorkieRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CheckService_ServiceDesc is the grpc.ServiceDesc for CheckService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CheckService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "codepair.v1.CheckService",
	HandlerType: (*CheckServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckNameConflict",
			Handler:    _CheckService_CheckNameConflict_Handler,
		},
		{
			MethodName: "CheckYorkie",
			Handler:    _CheckService_CheckYorkie_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "codepair/v1/check.proto",
}
