package entity

import "time"

// Visitor represents a visitor record in the hello repository.
type Visitor struct {
	ID        ID        `bson:"_id,omitempty"` // Auto-generated by MongoDB if empty.
	Nickname  string    `bson:"nickname"`      // Visitor's nickname.
	CreatedAt time.Time `bson:"created_at"`    // Timestamp when the record was created.
	UpdatedAt time.Time `bson:"updated_at"`    // Timestamp when the record was last updated.
}
