package database

import "time"

// Visitor represents a visitor record in the hello repository.
type Visitor struct {
	ID        string    `bson:"_id,omitempty"` // Auto-generated by MongoDB if empty.
	Nickname  string    `bson:"nickname"`      // Visitor's nickname.
	CreatedAt time.Time `bson:"created_at"`    // Timestamp when the record was created.
	UpdatedAt time.Time `bson:"updated_at"`    // Timestamp when the record was last updated.
}

// Hello defines the interface for CRUD operations on visitor records.
type Hello interface {
	// CreateVisitor creates a new visitor record.
	// It accepts a Visitor object and returns an error if creation fails.
	CreateVisitor(visitor Visitor) error

	// FindVisitor retrieves a visitor record by its unique identifier.
	// It returns the Visitor and an error if the record cannot be found.
	FindVisitor(id string) (Visitor, error)

	// UpdateVisitor updates an existing visitor record.
	// It accepts a Visitor object (including its ID) and returns an error if the update fails.
	UpdateVisitor(visitor Visitor) error

	// DeleteVisitor removes a visitor record by its unique identifier.
	// It returns an error if the deletion operation fails.
	DeleteVisitor(id string) error
}
