name: electron-build
on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node-version: [18.x]

    defaults:
      run:
        working-directory: ./native

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Set up pnpm
        uses: pnpm/action-setup@v4

      - name: Install Dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Build Electron App
        run: pnpm run build

      - name: Build and publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pnpm run electron-builder --publish always

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./release/**/*.exe
            ./release/**/*.dmg
            ./release/**/*.AppImage
            ./release/**/*.yml
            ./release/latest*.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
